<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ethnic/Civic Nationalism BES Wave 11</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="EFA:CFA_ethnic_civic_W11_files/libs/clipboard/clipboard.min.js"></script>
<script src="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/popper.min.js"></script>
<script src="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/anchor.min.js"></script>
<link href="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="EFA:CFA_ethnic_civic_W11_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="EFA:CFA_ethnic_civic_W11_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="EFA:CFA_ethnic_civic_W11_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="EFA:CFA_ethnic_civic_W11_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ethnic/Civic Nationalism BES Wave 11</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="explanatory-factor-analysis" class="level1">
<h1>Explanatory Factor Analysis</h1>
<p>Wave 11 of the British Election Study Internet Panel contains the most detailed battery on national identity across the entire series, providing a unique opportunity to distinguish empirically between ethnic and civic conceptions of British nationalism. This wave includes eight items measuring beliefs about who counts as “truly British,” with 2 indicators reflecting ethnic criteria (being born in Britain and being Christian) and four reflecting civic criteria (speaking English, respecting British laws, following British customs, and feeling British). Living in Britain and holding British citizenship were excluded from the analysis due to the lack of a clear theoretical background to add them into civic/ethnic criteria. These items, collected simultaneously in a single fieldwork period, allow for a consistent latent-structure analysis free from cross-wave measurement noise.</p>
<p>The goal of this brief report is to examine the empirical structure of these nationalism indicators in Wave 11, assess whether they cluster into distinct latent dimensions, and extract reliable factor scores. These scores will be used in subsequent analyses to test how different forms of national identity interact with economic conditions in shaping attitudes toward immigration.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(nat11, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    britBornHereW11 britChristianW11 britSpeakEnglishW11
britBornHereW11           1.0000000        0.4227805           0.3235898
britChristianW11          0.4227805        1.0000000           0.1787081
britSpeakEnglishW11       0.3235898        0.1787081           1.0000000
britCustomsW11            0.3818117        0.3236836           0.4593190
britRespectLawW11         0.2538262        0.1436993           0.4970865
britFeelBritishW11        0.4073958        0.2722961           0.3889655
                    britCustomsW11 britRespectLawW11 britFeelBritishW11
britBornHereW11          0.3818117         0.2538262          0.4073958
britChristianW11         0.3236836         0.1436993          0.2722961
britSpeakEnglishW11      0.4593190         0.4970865          0.3889655
britCustomsW11           1.0000000         0.3936618          0.4296220
britRespectLawW11        0.3936618         1.0000000          0.4163004
britFeelBritishW11       0.4296220         0.4163004          1.0000000</code></pre>
</div>
</div>
<p>The 2 ethnic nationalism items: <em>born in Britain</em>, and <em>Christian</em>, exhibit moderate to strong positive correlations with one another (0.27 to 0.7), indicating that they tap a shared underlying construct centered on origin-based and ascriptive membership criteria. Similarly, the four civic nationalism items: <em>speak English</em>, <em>follow British customs</em>, <em>respect British law</em>, and <em>feel British</em>, also correlate moderately among themselves (0.39 to 0.5), reflecting a distinct dimension based on behavioral and norms-based criteria. Cross-cluster correlations are consistently weaker: ethnic items correlate with civic items in the 0.17 to 0.41 range, suggesting related but clearly separable constructs. Overall, the correlation structure shows two internally cohesive clusters with weaker between-cluster associations, providing strong initial evidence for a two-dimensional latent structure that distinguishes ethnic from civic conceptions of national identity in the BES wave 11.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EFA-CFA_ethnic_civic_W11_files/figure-html/fa1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  3  and the number of components =  NA </code></pre>
</div>
</div>
<p>Parallel analysis of the revised item set suggests the presence of up to three factors, as the first three observed eigenvalues marginally exceed those obtained from simulated random data. However, inspection of the scree plot reveals a clear and steep drop after the second factor, with the third eigenvalue lying very close to the noise threshold and contributing negligible additional variance. Given the limited number of indicators, the small magnitude of the third eigenvalue, and strong theoretical expectations distinguishing ethnic and civic conceptions of national identity, the parallel analysis is best interpreted as supporting the retention of a <strong>two-factor solution</strong>. Accordingly, subsequent analyses focus on two latent dimensions, while treating any additional factors suggested by the parallel analysis as statistical noise rather than substantively meaningful constructs.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  ml
Call: fa(r = nat11, nfactors = 2, rotate = "oblimin", fm = "ml")
Standardized loadings (pattern matrix) based upon correlation matrix
                      ML1   ML2   h2   u2 com
britBornHereW11      0.11  0.63 0.48 0.52 1.1
britChristianW11    -0.09  0.67 0.40 0.60 1.0
britSpeakEnglishW11  0.70  0.02 0.50 0.50 1.0
britCustomsW11       0.46  0.30 0.44 0.56 1.7
britRespectLawW11    0.75 -0.09 0.50 0.50 1.0
britFeelBritishW11   0.44  0.29 0.41 0.59 1.7

                       ML1  ML2
SS loadings           1.59 1.14
Proportion Var        0.26 0.19
Cumulative Var        0.26 0.45
Proportion Explained  0.58 0.42
Cumulative Proportion 0.58 1.00

 With factor correlations of 
     ML1  ML2
ML1 1.00 0.51
ML2 0.51 1.00

Mean item complexity =  1.3
Test of the hypothesis that 2 factors are sufficient.

df null model =  15  with the objective function =  1.39 with Chi Square =  169757.1
df of  the model are 4  and the objective function was  0.01 

The root mean square of the residuals (RMSR) is  0.02 
The df corrected root mean square of the residuals is  0.03 

The harmonic n.obs is  29137 with the empirical chi square  245.09  with prob &lt;  7.4e-52 
The total n.obs was  122372  with Likelihood Chi Square =  1809.67  with prob &lt;  0 

Tucker Lewis Index of factoring reliability =  0.96
RMSEA index =  0.061  and the 90 % confidence intervals are  0.058 0.063
BIC =  1762.81
Fit based upon off diagonal values = 1
Measures of factor score adequacy             
                                                   ML1  ML2
Correlation of (regression) scores with factors   0.87 0.83
Multiple R square of scores with factors          0.76 0.68
Minimum correlation of possible factor scores     0.52 0.37</code></pre>
</div>
</div>
<p>A two-factor exploratory factor analysis estimated by maximum likelihood with oblimin rotation provides a coherent representation of the revised national identity battery. The two factors have SS loadings of 1.59 and 1.14, explaining 26% and 19% of the total variance, respectively, and 45% cumulatively. The factors are moderately correlated (r = 0.51), indicating that ethnic and civic conceptions of national identity are related but empirically distinct. Model fit is good by conventional standards: the RMSR is low (0.02), the Tucker–Lewis Index of factoring reliability is high (0.96), and the RMSEA is 0.061 with a narrow 90% confidence interval (0.058–0.063). Mean item complexity is modest (1.3), suggesting limited cross-loading and a well-defined factor structure. Measures of factor score adequacy indicate that regression-based scores are reliable, with correlations of 0.87 and 0.83 with the latent factors and substantial explained variance (R² = 0.76 and 0.68). Overall, the EFA supports a two-dimensional latent structure and provides a sound basis for confirmatory modeling.</p>
<section id="confirmatory-factor-analysis" class="level2">
<h2 class="anchored" data-anchor-id="confirmatory-factor-analysis">Confirmatory Factor Analysis</h2>
<p><strong>Model 1: One-factor nationalism.</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-20 ended normally after 10 iterations

  Estimator                                       DWLS
  Optimization method                           NLMINB
  Number of model parameters                        24

                                                  Used       Total
  Number of observations                         30305      122372
  Number of missing patterns                        61            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                              2241.553    3727.789
  Degrees of freedom                                 9           9
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  0.601
  Shift parameter                                            0.594
    simple second-order correction                                

Model Test Baseline Model:

  Test statistic                            108701.653   77984.112
  Degrees of freedom                                15          15
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.394

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.979       0.952
  Tucker-Lewis Index (TLI)                       0.966       0.921
                                                                  
  Robust Comparative Fit Index (CFI)                         0.886
  Robust Tucker-Lewis Index (TLI)                            0.810

Root Mean Square Error of Approximation:

  RMSEA                                          0.090       0.117
  90 Percent confidence interval - lower         0.087       0.114
  90 Percent confidence interval - upper         0.094       0.120
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000       1.000
                                                                  
  Robust RMSEA                                               0.178
  90 Percent confidence interval - lower                     0.173
  90 Percent confidence interval - upper                     0.184
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.069       0.069

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                           Robust.sem
  Information                                 Expected
  Information saturated (h1) model        Unstructured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Nationalism =~                                                        
    britBornHerW11    0.663    0.004  151.174    0.000    0.663    0.663
    britChristnW11    0.554    0.006  100.648    0.000    0.554    0.554
    brtSpkEnglsW11    0.791    0.005  169.433    0.000    0.791    0.791
    britCustomsW11    0.747    0.004  178.982    0.000    0.747    0.747
    britRspctLwW11    0.772    0.005  149.770    0.000    0.772    0.772
    britFlBrtshW11    0.715    0.004  161.839    0.000    0.715    0.715

Thresholds:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    brtBrnHrW11|t1   -1.004    0.009 -114.067    0.000   -1.004   -1.004
    brtBrnHrW11|t2    0.008    0.007    1.094    0.274    0.008    0.008
    brtBrnHrW11|t3    0.857    0.008  102.533    0.000    0.857    0.857
    brtChrstnW11|1   -0.009    0.007   -1.219    0.223   -0.009   -0.009
    brtChrstnW11|2    0.803    0.008   97.027    0.000    0.803    0.803
    brtChrstnW11|3    1.540    0.012  133.008    0.000    1.540    1.540
    brtSpkEngW11|1   -2.423    0.024 -101.961    0.000   -2.423   -2.423
    brtSpkEngW11|2   -1.860    0.014 -130.834    0.000   -1.860   -1.860
    brtSpkEngW11|3   -0.670    0.008  -85.392    0.000   -0.670   -0.670
    brtCstmsW11|t1   -2.022    0.016 -123.813    0.000   -2.022   -2.022
    brtCstmsW11|t2   -1.012    0.009 -114.905    0.000   -1.012   -1.012
    brtCstmsW11|t3    0.205    0.007   27.977    0.000    0.205    0.205
    brtRspctLW11|1   -2.440    0.024 -100.532    0.000   -2.440   -2.440
    brtRspctLW11|2   -1.993    0.016 -125.610    0.000   -1.993   -1.993
    brtRspctLW11|3   -0.862    0.008 -103.703    0.000   -0.862   -0.862
    brtFlBrtsW11|1   -1.738    0.013 -131.734    0.000   -1.738   -1.738
    brtFlBrtsW11|2   -1.080    0.009 -118.339    0.000   -1.080   -1.080
    brtFlBrtsW11|3    0.086    0.007   11.650    0.000    0.086    0.086

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .britBornHerW11    0.560                               0.560    0.560
   .britChristnW11    0.694                               0.694    0.694
   .brtSpkEnglsW11    0.374                               0.374    0.374
   .britCustomsW11    0.442                               0.442    0.442
   .britRspctLwW11    0.404                               0.404    0.404
   .britFlBrtshW11    0.488                               0.488    0.488
    Nationalism       1.000                               1.000    1.000</code></pre>
</div>
</div>
<p>The one-factor confirmatory model, in which all eight indicators load on a single latent nationalism construct, performs poorly despite high incremental fit indices. While the Comparative Fit Index (CFI = 0.976) and Tucker–Lewis Index (TLI = 0.966) appear acceptable, absolute fit measures indicate substantial misspecification. The RMSEA is unacceptably high (0.113; 90% CI: 0.111–0.115), and the SRMR exceeds conventional thresholds (0.086), with robust RMSEA estimates indicating even more severe misfit. This pattern—high CFI/TLI combined with poor RMSEA—is typical in very large samples and reflects the inability of a unidimensional model to reproduce the observed covariance structure. Although all indicators load strongly and significantly on the latent factor, the poor absolute fit clearly rejects the hypothesis that beliefs about who counts as “truly British” can be represented by a single underlying dimension. These results motivate the estimation of multidimensional models that allow for distinct but correlated forms of national identity.</p>
<p><strong>Model 2: Two correlated factors (ethnic vs civic)</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-20 ended normally after 13 iterations

  Estimator                                       DWLS
  Optimization method                           NLMINB
  Number of model parameters                        25

                                                  Used       Total
  Number of observations                         30305      122372
  Number of missing patterns                        61            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               894.399    1601.651
  Degrees of freedom                                 8           8
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  0.559
  Shift parameter                                            0.400
    simple second-order correction                                

Model Test Baseline Model:

  Test statistic                            108701.653   77984.112
  Degrees of freedom                                15          15
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.394

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.992       0.980
  Tucker-Lewis Index (TLI)                       0.985       0.962
                                                                  
  Robust Comparative Fit Index (CFI)                         0.944
  Robust Tucker-Lewis Index (TLI)                            0.895

Root Mean Square Error of Approximation:

  RMSEA                                          0.060       0.081
  90 Percent confidence interval - lower         0.057       0.078
  90 Percent confidence interval - upper         0.064       0.084
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.000       0.706
                                                                  
  Robust RMSEA                                               0.133
  90 Percent confidence interval - lower                     0.127
  90 Percent confidence interval - upper                     0.139
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.044       0.044

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                           Robust.sem
  Information                                 Expected
  Information saturated (h1) model        Unstructured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Ethnic =~                                                             
    britBornHerW11    0.820    0.006  137.131    0.000    0.820    0.820
    britChristnW11    0.632    0.006  109.554    0.000    0.632    0.632
  Civic =~                                                              
    brtSpkEnglsW11    0.803    0.005  172.098    0.000    0.803    0.803
    britCustomsW11    0.763    0.004  180.870    0.000    0.763    0.763
    britRspctLwW11    0.783    0.005  152.375    0.000    0.783    0.783
    britFlBrtshW11    0.728    0.004  161.940    0.000    0.728    0.728

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Ethnic ~~                                                             
    Civic             0.737    0.006  118.496    0.000    0.737    0.737

Thresholds:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    brtBrnHrW11|t1   -1.004    0.009 -114.067    0.000   -1.004   -1.004
    brtBrnHrW11|t2    0.008    0.007    1.094    0.274    0.008    0.008
    brtBrnHrW11|t3    0.857    0.008  102.533    0.000    0.857    0.857
    brtChrstnW11|1   -0.009    0.007   -1.219    0.223   -0.009   -0.009
    brtChrstnW11|2    0.803    0.008   97.027    0.000    0.803    0.803
    brtChrstnW11|3    1.540    0.012  133.008    0.000    1.540    1.540
    brtSpkEngW11|1   -2.423    0.024 -101.961    0.000   -2.423   -2.423
    brtSpkEngW11|2   -1.860    0.014 -130.834    0.000   -1.860   -1.860
    brtSpkEngW11|3   -0.670    0.008  -85.392    0.000   -0.670   -0.670
    brtCstmsW11|t1   -2.022    0.016 -123.813    0.000   -2.022   -2.022
    brtCstmsW11|t2   -1.012    0.009 -114.905    0.000   -1.012   -1.012
    brtCstmsW11|t3    0.205    0.007   27.977    0.000    0.205    0.205
    brtRspctLW11|1   -2.440    0.024 -100.532    0.000   -2.440   -2.440
    brtRspctLW11|2   -1.993    0.016 -125.610    0.000   -1.993   -1.993
    brtRspctLW11|3   -0.862    0.008 -103.703    0.000   -0.862   -0.862
    brtFlBrtsW11|1   -1.738    0.013 -131.734    0.000   -1.738   -1.738
    brtFlBrtsW11|2   -1.080    0.009 -118.339    0.000   -1.080   -1.080
    brtFlBrtsW11|3    0.086    0.007   11.650    0.000    0.086    0.086

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .britBornHerW11    0.328                               0.328    0.328
   .britChristnW11    0.601                               0.601    0.601
   .brtSpkEnglsW11    0.355                               0.355    0.355
   .britCustomsW11    0.418                               0.418    0.418
   .britRspctLwW11    0.387                               0.387    0.387
   .britFlBrtshW11    0.470                               0.470    0.470
    Ethnic            1.000                               1.000    1.000
    Civic             1.000                               1.000    1.000</code></pre>
</div>
</div>
<p>The two-factor confirmatory model, distinguishing ethnic and civic conceptions of national identity, fits the data well and represents a substantial improvement over the unidimensional specification. Incremental fit indices are high (CFI = 0.992; TLI = 0.985), while absolute fit measures fall within acceptable ranges (RMSEA = 0.060, 90% CI: 0.057–0.064; SRMR = 0.044). Standardized factor loadings are large and statistically significant for all indicators, with the ethnic factor defined by being born in Britain (0.820) and being Christian (0.632), and the civic factor defined by speaking English, respecting British laws, following British customs, and feeling British (loadings between 0.728 and 0.803). The latent factors are strongly but not perfectly correlated (r = 0.737), indicating substantial overlap while remaining empirically distinct. Overall, these results confirm the presence of two related yet separable dimensions of national identity and provide a well-behaved measurement model for subsequent analyses.</p>
<p><strong>Model 3: EFA-motivated cross-loading (citizenship)</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Ethnic =~ britBornHereW11 + britChristianW11
Civic  =~ britSpeakEnglishW11 + britCustomsW11 + britRespectLawW11 + britFeelBritishW11
Ethnic ~~ Civic</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-20 ended normally after 13 iterations

  Estimator                                       DWLS
  Optimization method                           NLMINB
  Number of model parameters                        25

                                                  Used       Total
  Number of observations                         30305      122372
  Number of missing patterns                        61            

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               894.399    1601.651
  Degrees of freedom                                 8           8
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  0.559
  Shift parameter                                            0.400
    simple second-order correction                                

Model Test Baseline Model:

  Test statistic                            108701.653   77984.112
  Degrees of freedom                                15          15
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.394

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.992       0.980
  Tucker-Lewis Index (TLI)                       0.985       0.962
                                                                  
  Robust Comparative Fit Index (CFI)                         0.944
  Robust Tucker-Lewis Index (TLI)                            0.895

Root Mean Square Error of Approximation:

  RMSEA                                          0.060       0.081
  90 Percent confidence interval - lower         0.057       0.078
  90 Percent confidence interval - upper         0.064       0.084
  P-value H_0: RMSEA &lt;= 0.050                    0.000       0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.000       0.706
                                                                  
  Robust RMSEA                                               0.133
  90 Percent confidence interval - lower                     0.127
  90 Percent confidence interval - upper                     0.139
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.044       0.044

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                           Robust.sem
  Information                                 Expected
  Information saturated (h1) model        Unstructured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Ethnic =~                                                             
    britBornHerW11    0.820    0.006  137.131    0.000    0.820    0.820
    britChristnW11    0.632    0.006  109.554    0.000    0.632    0.632
  Civic =~                                                              
    brtSpkEnglsW11    0.803    0.005  172.098    0.000    0.803    0.803
    britCustomsW11    0.763    0.004  180.870    0.000    0.763    0.763
    britRspctLwW11    0.783    0.005  152.375    0.000    0.783    0.783
    britFlBrtshW11    0.728    0.004  161.940    0.000    0.728    0.728

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Ethnic ~~                                                             
    Civic             0.737    0.006  118.496    0.000    0.737    0.737

Thresholds:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    brtBrnHrW11|t1   -1.004    0.009 -114.067    0.000   -1.004   -1.004
    brtBrnHrW11|t2    0.008    0.007    1.094    0.274    0.008    0.008
    brtBrnHrW11|t3    0.857    0.008  102.533    0.000    0.857    0.857
    brtChrstnW11|1   -0.009    0.007   -1.219    0.223   -0.009   -0.009
    brtChrstnW11|2    0.803    0.008   97.027    0.000    0.803    0.803
    brtChrstnW11|3    1.540    0.012  133.008    0.000    1.540    1.540
    brtSpkEngW11|1   -2.423    0.024 -101.961    0.000   -2.423   -2.423
    brtSpkEngW11|2   -1.860    0.014 -130.834    0.000   -1.860   -1.860
    brtSpkEngW11|3   -0.670    0.008  -85.392    0.000   -0.670   -0.670
    brtCstmsW11|t1   -2.022    0.016 -123.813    0.000   -2.022   -2.022
    brtCstmsW11|t2   -1.012    0.009 -114.905    0.000   -1.012   -1.012
    brtCstmsW11|t3    0.205    0.007   27.977    0.000    0.205    0.205
    brtRspctLW11|1   -2.440    0.024 -100.532    0.000   -2.440   -2.440
    brtRspctLW11|2   -1.993    0.016 -125.610    0.000   -1.993   -1.993
    brtRspctLW11|3   -0.862    0.008 -103.703    0.000   -0.862   -0.862
    brtFlBrtsW11|1   -1.738    0.013 -131.734    0.000   -1.738   -1.738
    brtFlBrtsW11|2   -1.080    0.009 -118.339    0.000   -1.080   -1.080
    brtFlBrtsW11|3    0.086    0.007   11.650    0.000    0.086    0.086

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .britBornHerW11    0.328                               0.328    0.328
   .britChristnW11    0.601                               0.601    0.601
   .brtSpkEnglsW11    0.355                               0.355    0.355
   .britCustomsW11    0.418                               0.418    0.418
   .britRspctLwW11    0.387                               0.387    0.387
   .britFlBrtshW11    0.470                               0.470    0.470
    Ethnic            1.000                               1.000    1.000
    Civic             1.000                               1.000    1.000</code></pre>
</div>
</div>
<p>Allowing for a cross-loading does not alter the fit or substantive conclusions of the two-factor model. Fit indices are identical to those obtained in the baseline two-factor specification (CFI = 0.992; TLI = 0.985; RMSEA = 0.060; SRMR = 0.044), and the pattern and magnitude of standardized factor loadings remain unchanged. The correlation between the ethnic and civic dimensions is also identical (r = 0.737), indicating that permitting an additional loading does not reduce shared variance between the factors or alleviate residual misfit. These results suggest that, once ethnic nationalism is defined narrowly in strictly ascriptive terms, there is no empirical gain from introducing cross-loadings. Accordingly, the more parsimonious two-factor model without cross-loadings is retained as the preferred specification.</p>
<p>Fit comparison table</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  Model                                  cfi   tli  rmsea   srmr
  &lt;chr&gt;                                &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 1-factor                             0.979 0.966 0.0905 0.0691
2 2-factor (Ethnic/Civic)              0.992 0.985 0.0605 0.0442
3 2-factor + citizenship cross-loading 0.992 0.985 0.0605 0.0442</code></pre>
</div>
</div>
<p>Table X summarizes the comparative fit of the confirmatory factor models. The one-factor specification exhibits poor absolute fit, with an RMSEA of 0.113 and SRMR of 0.087, despite relatively high incremental fit indices—confirming that a unidimensional nationalism construct is inadequate. The two-factor model distinguishing ethnic and civic nationalism represents a substantial improvement, achieving excellent incremental fit (CFI = 0.992; TLI = 0.985) and acceptable absolute fit (RMSEA = 0.061; SRMR = 0.044). Allowing for a citizenship cross-loading does not improve model fit, yielding identical fit indices to the baseline two-factor specification. On grounds of parsimony and theoretical clarity, the two-factor model without cross-loadings is therefore retained as the preferred measurement model.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>