<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Appendix: Temporal Stability of the Nationalism–ATI Relationship</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Sanity_checks_files/libs/clipboard/clipboard.min.js"></script>
<script src="Sanity_checks_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Sanity_checks_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Sanity_checks_files/libs/quarto-html/popper.min.js"></script>
<script src="Sanity_checks_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Sanity_checks_files/libs/quarto-html/anchor.min.js"></script>
<link href="Sanity_checks_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Sanity_checks_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Sanity_checks_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Sanity_checks_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Sanity_checks_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Sanity_checks.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Appendix: Temporal Stability of the Nationalism–ATI Relationship</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This appendix aims to verify whether the relationship between national identity and attitudes toward immigration (ATI) is temporally stable, before introducing economic moderators. Specifically, we examine whether ATI varies over time as a function of national identity, as formalised by an interaction between Britishness and time.</p>
<p>The analytical strategy proceeds in three steps. First, I estimate respondent fixed-effects models interacting Britishness with calendar time to test for monotonic temporal drift in the nationalism–ATI relationship. Second, I estimate more flexible specifications that allow the effect of Britishness to vary freely across survey waves, capturing non-linear or big events changes. Third, identical temporal-stability checks across alternative ATI measures as a robustness exercise, while treating immigration self-placement (<code>immigSelf</code>) as the primary outcome given its substantially broader temporal coverage and superior suitability for longitudinal analysis.</p>
<p>All models are estimated using the <code>feols()</code> function from the <strong>fixest</strong> package. This estimator implements linear fixed-effects models using the within transformation, efficiently absorbing respondent-specific fixed effects without explicitly including thousands of dummy variables. Respondent fixed effects ensure that identification relies exclusively on within-individual variation over time, netting out all time-invariant characteristics such as baseline ideology, demographics, or long-run identity traits. Standard errors are clustered at the respondent level, allowing for arbitrary heteroskedasticity and serial correlation within individuals over time. This estimation strategy is well established in applied panel-data research and is particularly appropriate for assessing temporal stability in longitudinal survey data.</p>
<p>1. Economic ATI: Britishness × time</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: immigEcon
Observations: 517,299
Fixed-effects: id: 82,988
Standard-errors: Clustered (id) 
                  Estimate Std. Error   t value   Pr(&gt;|t|)    
britishness       0.414713   0.931632  0.445147 6.5621e-01    
year              0.018996   0.002648  7.174667 7.3087e-13 ***
britishness:year -0.000217   0.000461 -0.469706 6.3857e-01    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.907486     Adj. R2: 0.718912
                 Within R2: 0.003254</code></pre>
</div>
</div>
<p>This model estimates the within-respondent relationship between national identity and economic attitudes toward immigration using a respondent fixed-effects specification with clustered standard errors. The inclusion of individual fixed effects ensures that identification relies exclusively on within-person change over time, netting out all time-invariant characteristics. The model is estimated on a large panel of 82,988 respondents. While the overall fit is high due to the absorption of stable individual differences (adjusted R² = 0.72), the within-respondent explanatory power of the model is very limited (within R² = 0.003). This indicates that temporal variation explains only a small share of changes in economic ATI within individuals. Importantly, this pattern is consistent with the interpretation that the association between Britishness and economic immigration attitudes is broadly stable over time, rather than driven by secular temporal drift, motivating the analysis of contextual moderators in subsequent models.</p>
<p>2. Economic ATI: Britishness × wave (flexible)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: immigEcon
Observations: 517,299
Fixed-effects: id: 82,988
Standard-errors: Clustered (id) 
                      Estimate Std. Error    t value   Pr(&gt;|t|)    
wave::1:britishness  -0.105789   0.002410 -43.889392  &lt; 2.2e-16 ***
wave::2:britishness  -0.101630   0.002358 -43.091932  &lt; 2.2e-16 ***
wave::3:britishness  -0.128669   0.002385 -53.952634  &lt; 2.2e-16 ***
wave::4:britishness  -0.070193   0.002280 -30.788347  &lt; 2.2e-16 ***
wave::7:britishness  -0.077187   0.002296 -33.623986  &lt; 2.2e-16 ***
wave::8:britishness  -0.069792   0.002291 -30.461878  &lt; 2.2e-16 ***
wave::10:britishness  0.002283   0.002330   0.979749 3.2721e-01    
wave::13:britishness  0.028667   0.005656   5.068784 4.0122e-07 ***
wave::14:britishness  0.041641   0.002252  18.492504  &lt; 2.2e-16 ***
wave::15:britishness  0.075930   0.002329  32.606826  &lt; 2.2e-16 ***
wave::16:britishness  0.062094   0.002304  26.946781  &lt; 2.2e-16 ***
wave::17:britishness  0.063849   0.002216  28.812639  &lt; 2.2e-16 ***
wave::20:britishness  0.083913   0.002357  35.594567  &lt; 2.2e-16 ***
wave::21:britishness  0.024873   0.002356  10.555986  &lt; 2.2e-16 ***
wave::22:britishness  0.006333   0.002394   2.645480 8.1590e-03 ** 
wave::23:britishness  0.008725   0.002364   3.690630 2.2384e-04 ***
wave::25:britishness -0.021285   0.002451  -8.684279  &lt; 2.2e-16 ***
wave::26:britishness -0.062704   0.002408 -26.034961  &lt; 2.2e-16 ***
wave::27:britishness -0.043117   0.002352 -18.335090  &lt; 2.2e-16 ***
wave::30:britishness -0.102076   0.002454 -41.588506  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.851067     Adj. R2: 0.752767
                 Within R2: 0.123338</code></pre>
</div>
</div>
<p>This specification allows the effect of Britishness on economic attitudes toward immigration to vary flexibly across survey waves by interacting national identity with wave indicators, while retaining respondent fixed effects and clustering standard errors at the individual level. Compared to the linear time-interaction model, this more flexible specification explains substantially more within-respondent variation (within R² = 0.12), indicating meaningful heterogeneity in the strength of the nationalism–economic ATI relationship across political periods. Importantly, these wave-specific effects do not exhibit a monotonic trend over time; instead, they fluctuate across waves, suggesting episodic strengthening and weakening of the association rather than secular drift. This pattern reinforces the interpretation that temporal variation in economic ATI is context-dependent and motivates the introduction of economic conditions as moderators in subsequent analyses.</p>
<p>3. Cultural ATI: Britishness × time</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: immigCultural
Observations: 355,926
Fixed-effects: id: 71,802
Standard-errors: Clustered (id) 
                  Estimate Std. Error  t value  Pr(&gt;|t|)    
britishness      -4.042724   1.291704 -3.12976 0.0017502 ** 
year              0.053305   0.003694 14.43181 &lt; 2.2e-16 ***
britishness:year  0.001992   0.000640  3.11122 0.0018639 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.895357     Adj. R2: 0.757368
                 Within R2: 0.022428</code></pre>
</div>
</div>
<p>This model examines the within-respondent relationship between national identity and cultural attitudes toward immigration using a respondent fixed-effects specification with clustered standard errors. The analysis is based on 71,802 respondents. As in the other specifications, individual fixed effects absorb stable personal characteristics, yielding a high adjusted R² (0.76). However, the within-respondent explanatory power remains modest (within R² = 0.022), indicating that calendar time and its interaction with Britishness account for only a limited share of changes in cultural ATI within individuals. This suggests that, while the nationalism–cultural ATI relationship may evolve gradually over time, it does not exhibit strong mechanical drift, reinforcing the interpretation that temporal variation is relatively constrained and likely shaped by contextual factors rather than by time itself.</p>
<p>4. Immigration preference: Britishness × time</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: immigSelf
Observations: 453,078
Fixed-effects: id: 73,798
Standard-errors: Clustered (id) 
                      Estimate Std. Error   t value   Pr(&gt;|t|)    
wave::8:britishness  -0.035091   0.001936 -18.12662  &lt; 2.2e-16 ***
wave::9:britishness  -0.013820   0.002000  -6.90991 4.8886e-12 ***
wave::10:britishness -0.017057   0.002055  -8.30155  &lt; 2.2e-16 ***
wave::13:britishness -0.022018   0.007591  -2.90062 3.7254e-03 ** 
wave::14:britishness  0.065027   0.002109  30.83568  &lt; 2.2e-16 ***
wave::15:britishness  0.089138   0.002272  39.23715  &lt; 2.2e-16 ***
wave::16:britishness  0.097761   0.002285  42.78054  &lt; 2.2e-16 ***
wave::17:britishness  0.082403   0.002166  38.03948  &lt; 2.2e-16 ***
wave::20:britishness  0.117936   0.002337  50.45401  &lt; 2.2e-16 ***
wave::21:britishness  0.116882   0.002366  49.40097  &lt; 2.2e-16 ***
wave::22:britishness  0.115988   0.002471  46.94418  &lt; 2.2e-16 ***
wave::23:britishness  0.152057   0.002451  62.03101  &lt; 2.2e-16 ***
wave::25:britishness  0.074813   0.002512  29.78003  &lt; 2.2e-16 ***
wave::26:britishness -0.005314   0.002380  -2.23289 2.5560e-02 *  
wave::27:britishness  0.006112   0.002319   2.63506 8.4141e-03 ** 
wave::29:britishness -0.011745   0.002384  -4.92587 8.4167e-07 ***
wave::30:britishness -0.036763   0.002449 -15.01093  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 1.24678     Adj. R2: 0.777356
                Within R2: 0.057164</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sanity_checks_files/figure-html/4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Focusing on immigration self-placement (<code>immigSelf</code>), the outcome with the most extensive temporal coverage, the fixed-effects models indicate meaningful but non-monotonic variation in the relationship between national identity and immigration preferences over time. While the overall within-individual explanatory power of the model is small (within R² = 0.057), the wave-specific estimates reveal substantial heterogeneity in the strength of the Britishness effect across survey waves. As illustrated in the wave-interaction plot, the association between Britishness and restrictive immigration preferences intensifies in specific mid-period waves before attenuating in later waves, without exhibiting a persistent upward or downward trend. This pattern suggests episodic reinforcement rather than secular drift, consistent with the interpretation that changes in the nationalism–ATI relationship are driven by context-specific political or economic conditions rather than by time itself.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>